import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const intro = readFileSync(join(root, 'src', 'intro.js'), 'utf8');
const css = readFileSync(join(root, 'src', 'style-explore.css'), 'utf8');
const main = readFileSync(join(root, 'src', 'main.js'), 'utf8');
const version = readFileSync(join(root, 'src', 'research', 'version.js'), 'utf8');
const logger = readFileSync(join(root, 'src', 'research', 'logger.js'), 'utf8');
const taxonomy = readFileSync(join(root, 'src', 'research', 'event-taxonomy.js'), 'utf8');
const session = readFileSync(join(root, 'src', 'research', 'session.js'), 'utf8');
const backendApi = readFileSync(join(root, 'src', 'research', 'api.js'), 'utf8');
const backendSchema = readFileSync(join(root, 'docs', 'supabase-schema-v1.sql'), 'utf8');
const html = readFileSync(join(root, 'index.html'), 'utf8');

function blockBetween(source, start, end) {
  const startIdx = source.indexOf(start);
  assert.notEqual(startIdx, -1, `Missing block start: ${start}`);
  const endIdx = source.indexOf(end, startIdx);
  assert.notEqual(endIdx, -1, `Missing block end after ${start}: ${end}`);
  return source.slice(startIdx, endIdx);
}

const yearLabels = blockBetween(intro, 'const YEAR_LABELS = {', '};\n  function yearToLabel');
[1870, 1873, 1875, 1882, 1884].forEach((year) => {
  assert.match(yearLabels, new RegExp(`${year}:`), `YEAR_LABELS should include ${year}`);
});
assert.doesNotMatch(yearLabels, /1885:\s*'大清 光緒十一年 · 乙酉'/, 'YEAR_LABELS should not keep 1885 as the Mawei pinned year');

const resetGameState = blockBetween(intro, 'function resetGameState(route) {', '\n  }\n\n  // 路線起始稟賦');
assert.match(resetGameState, /gameState\.shownInterludes\s*=\s*\[\];/, 'New games should clear shown interludes');
assert.match(resetGameState, /gameState\.suspenses\s*=\s*\{\};/, 'New games should clear suspense state');

assert.match(css, /\.event-modal\s+\.em-card[\s\S]*max-height:\s*min\(92vh,\s*720px\)/, 'Event cards need a capped readable height');
assert.match(css, /\.event-modal\[data-kind="pinned"\]\s+\.em-image[\s\S]*height:\s*clamp\(150px,\s*26vh,\s*260px\)/, 'Pinned event images need a responsive height cap');
assert.match(css, /@media \(max-width:\s*700px\)[\s\S]*\.map-stats[\s\S]*position:\s*fixed/, 'Mobile map stats should use a dedicated fixed layout');
assert.match(css, /@media \(max-width:\s*700px\)[\s\S]*\.map-events[\s\S]*max-height:\s*34vh/, 'Mobile map events should be shortened for map visibility');
assert.match(html, /id="cityMissionSheet"/, 'City view should expose the richer bottom mission sheet');
assert.match(html, /id="cityMissionToggle"/, 'Mission sheet should have an expand/collapse control');
assert.match(html, /id="cityMissionObjective"/, 'Mission sheet should expose the current objective');
assert.match(html, /id="cityMissionNext"/, 'Mission sheet should expose the next action cue');
assert.match(html, /id="cityMissionFeedback"/, 'Mission sheet should expose return feedback after events');
assert.match(intro, /function getCityMissionState\(scene\)/, 'City mission state should be computed in one helper');
assert.match(intro, /function updateCityMissionSheet\(scene,\s*message\)/, 'City mission sheet should refresh with optional feedback');
assert.match(intro, /function setMissionSheetExpanded\(expanded\)/, 'Mission sheet should support explicit expand/collapse state');
assert.match(css, /\.city-mission-sheet/, 'Mission sheet CSS should be present');
assert.match(css, /@media \(max-width:\s*700px\)[\s\S]*\.city-mission-sheet/, 'Mobile mission sheet layout should be capped for map visibility');
assert.match(css, /\.city-mission-toggle[\s\S]*min-height:\s*44px/, 'Mission toggle should have a comfortable touch target');
assert.match(css, /\.hotspot[\s\S]*min-width:\s*44px[\s\S]*min-height:\s*44px/, 'City hotspots should expose comfortable touch targets');
assert.match(html, /id="hotspotObservation"/, 'City scene should include a lightweight hotspot observation layer');
assert.match(html, /id="hoText"/, 'Hotspot observation layer should expose text content');
assert.doesNotMatch(html, /class="ho-mark"|>目<\/span>/, 'Hotspot observation should not show a separate icon beside the copy');
assert.match(intro, /function showHotspotObservation\(hs,\s*spot\)/, 'Hotspots should show observation copy before entering evidence tasks');
assert.match(intro, /function hideHotspotObservation\(\)/, 'Hotspot observation should be dismissible');
assert.match(intro, /data-observation/, 'Hotspot buttons should carry observation text for hover/tap');
assert.match(css, /\.hotspot-observation[\s\S]*position:\s*absolute/, 'Observation copy should render as an in-scene floating layer');
assert.doesNotMatch(html, /id="emInquiryScaffold"/, 'Event modal should not expose a visible inquiry scaffold');
assert.doesNotMatch(html, /em-inquiry-label">案 由|em-inquiry-label">線 索|em-inquiry-label">局 勢/, 'Event modal should not show scaffold labels');
assert.doesNotMatch(html, /id="emDecisionTrace"/, 'Event payoff should not expose a decision-trace panel');
assert.doesNotMatch(html, /抉 擇 回 聲/, 'Event payoff should not show explicit decision-trace wording');
assert.doesNotMatch(html, /id="emRhythm"/, 'Event modal should not expose a rhythm rail');
assert.doesNotMatch(html, /<em>入境<\/em>|<em>抉擇<\/em>|<em>追問<\/em>|<em>回聲<\/em>/, 'Event modal should not show rhythm step labels');
assert.match(intro, /function getEventInquiryScaffold\(eventId,\s*ev\)/, 'Event inquiry scaffold should be generated by a helper');
assert.match(intro, /function getEvidenceRevealScaffold\(hs,\s*task\)/, 'Evidence reveal scaffold should be generated by a helper');
assert.match(intro, /function renderEvidenceRevealStep\(hs,\s*task,\s*step\)/, 'Evidence reveal should advance through explicit reveal steps');
assert.doesNotMatch(intro, /function getEvidenceInferenceChoices\(hs\)/, 'Evidence reveal should not expose axis-classification choices in the foreground');
assert.match(intro, /function getFrontstageGainLabel\(axis\)/, 'Foreground gain copy should be separated from internal axis codes');
assert.doesNotMatch(css, /\.em-inquiry-scaffold/, 'Event inquiry scaffold CSS should be removed from frontstage');
assert.doesNotMatch(css, /\.em-decision-trace/, 'Decision trace CSS should be removed from frontstage');
assert.doesNotMatch(css, /\.em-rhythm/, 'Event rhythm rail CSS should be removed from frontstage');
assert.doesNotMatch(css, /\.ev-inquiry-grid[\s\S]*display:\s*grid/, 'Evidence reveal should not expose a structured inquiry grid');
assert.doesNotMatch(css, /\.ev-progressive/, 'Evidence reveal should not show a staged scaffold container');
assert.doesNotMatch(css, /\.ev-reveal-rail/, 'Evidence reveal should not show staged rail UI');
assert.doesNotMatch(css, /\.ev-infer-choice/, 'Evidence reveal should not show a separate inference-choice layer');
assert.doesNotMatch(intro, /證 據 入 卷/, 'Evidence completion should not open a full archive page');
assert.doesNotMatch(intro, /ev-archive-card/, 'Evidence completion should not render an archive card');
assert.doesNotMatch(intro, /submit\.textContent\s*=\s*'入 局 →'/, 'Evidence completion should not require an entry button');
assert.match(intro, /function showEvidenceCollectedToast\(hs\)/, 'Evidence completion should show a brief confirmation');
assert.match(intro, /window\.setTimeout\(\(\) => finishEvidenceReveal\(hs\)/, 'Linked evidence should proceed automatically after confirmation');
assert.match(intro, /function stripDseTag\(text\)/, 'Visible text should pass through DSE tag stripping');
assert.doesNotMatch(intro, /DSE：[^'"]+['"]\s*\+/, 'Visible UI should not concatenate DSE labels into player-facing copy');
assert.match(intro, /if \(hasFoundHotspot\(cityKey,\s*hs\.id\)\) return;/, 'Completed hotspots should disappear from the scene');
assert.match(css, /\.hotspot::before[\s\S]*width:\s*22px[\s\S]*height:\s*22px/, 'Hotspot visible dot should be smaller than its hit area');
assert.match(css, /\.hotspot-observation[\s\S]*background:\s*rgba/, 'Observation tooltip should use translucent scene styling');
assert.doesNotMatch(html, /ribbon-seal--relic[^>]*>卯</, 'Intro should not show the old zodiac seal on the landing page');
assert.match(css, /\.screen--intro \.era-axis[\s\S]*writing-mode:\s*vertical-rl/, 'Landing page era axis should read as one vertical line');
assert.match(css, /\.screen--intro \.bottom-strip[\s\S]*pointer-events:\s*auto/, 'Landing page utility buttons should remain clickable');
assert.match(css, /\.screen\[aria-hidden="true"\][\s\S]*visibility:\s*hidden[\s\S]*pointer-events:\s*none\s*!important[\s\S]*\.screen\[aria-hidden="true"\] \*[\s\S]*pointer-events:\s*none\s*!important/, 'Hidden screens and their children must not intercept landing utility clicks');
assert.doesNotMatch(html, /id="audioStrip"|id="quoteAudio"|聆 聽|timeCode/, 'Landing page should not show the old quote/audio control in the bottom utility strip');
assert.match(css, /\.city-seal--hascontent:not\(\.city-seal--current\):not\(\.city-seal--target\) \.city-seal-box[\s\S]*fill:\s*rgba\(62,\s*82,\s*72/, 'Available side-visit cities should be visible without using target-city red');
assert.match(intro, /const MANAGED_MODAL_IDS = \[[\s\S]*'eventModal'[\s\S]*'evidenceTaskModal'[\s\S]*'achievementGallery'[\s\S]*'personGallery'[\s\S]*'letterModal'[\s\S]*\]/, 'A1 should define a managed modal registry for major overlays');
assert.match(intro, /function openManagedModal\(id,\s*options = \{\}\)[\s\S]*closeManagedModals[\s\S]*removeAttribute\('hidden'\)[\s\S]*refreshManagedModalState/, 'A1 should open modals through a shared layer helper');
assert.match(intro, /function hideManagedModal\(id\)[\s\S]*setAttribute\('hidden'[\s\S]*refreshManagedModalState/, 'A1 should hide modals through a shared layer helper');
assert.match(intro, /function closeTopManagedLayer\(\)[\s\S]*eventModal[\s\S]*evidenceTaskModal[\s\S]*achievementGallery[\s\S]*hotspotModal[\s\S]*seal-panel:not\(\[hidden\]\)/, 'A1 should close the top managed layer before falling through to city close');
assert.match(intro, /document\.addEventListener\('keydown'[\s\S]*closeTopManagedLayer\(\)[\s\S]*closeCityScene\(\)/, 'Escape should use the unified top-layer handler before closing the city scene');
assert.match(intro, /openManagedModal\('achievementGallery'[\s\S]*openManagedModal\('personGallery'/, 'Landing utility galleries should use the managed modal helper');
assert.match(intro, /openManagedModal\('eventModal'\)[\s\S]*hideManagedModal\('eventModal'\)/, 'Event modal should use managed open and close helpers');
assert.match(css, /--z-map-panel:[\s\S]*--z-event-modal:[\s\S]*--z-evidence-modal:[\s\S]*--z-gallery-modal:[\s\S]*--z-cutscene:/, 'A1 should define named z-index layer tokens');
assert.match(css, /\.event-modal[\s\S]*z-index:\s*var\(--z-event-modal\)/, 'Event modal should use the named event layer');
assert.match(css, /\.evidence-task-modal[\s\S]*z-index:\s*var\(--z-evidence-modal\)/, 'Evidence modal should use the named evidence layer');
assert.match(css, /\.achv-gallery[\s\S]*z-index:\s*var\(--z-gallery-modal\)/, 'Achievement/person galleries should use the named gallery layer');
assert.match(intro, /document\.addEventListener\('click'[\s\S]*#introAchv[\s\S]*#introPersons[\s\S]*showPersonGallery/, 'Landing page utility buttons should have delegated click handling');
assert.match(intro, /document\.addEventListener\('dragstart'[\s\S]*preventDefault\(\)/, 'Native image dragging should be disabled to prevent portrait drag ghosts');
assert.match(intro, /class="s2c-portrait"[\s\S]*draggable="false"/, 'Route portraits should be explicitly non-draggable');
assert.match(intro, /function primeIntroBgm\(\)/, 'Landing page should attempt to start background music on entry');
assert.match(intro, /window\.addEventListener\('pointerdown',\s*unlock/, 'Landing music should recover from browser autoplay blocking on first interaction');
assert.doesNotMatch(intro, /判斷軸線：/, 'Event payoff should avoid explicit axis-classification wording');
assert.doesNotMatch(html, /id="objectiveCard"|oc-card--flash|奉 旨|軍 機 處 鈐/, 'Post-cutscene entry should not include an extra edict/objective overlay');
assert.doesNotMatch(intro, /showObjectiveCard|timer\s*=\s*setTimeout\(finish,\s*1150\)/, 'New-game entry should not route through an edict flash helper');
assert.doesNotMatch(css, /objective-card|oc-card|oc-begin|oc-seal|oc-kicker/, 'Edict/objective card CSS should be removed after direct map entry');
assert.match(intro, /人物過場結束後直接揭示入場[\s\S]*runEntry\(\);/, 'New-game and continued-game routes should enter the existing map reveal directly');
assert.match(html, /局 勢 已 動，請 擇 一 條 自 強 之 路。/, 'B1 landing copy should foreground action rather than explanation');
assert.match(html, /入 局 啟 程/, 'B1 primary CTA should read as an immersive game entry');
assert.match(intro, /首 卷 路 線/, 'B1 first route should be framed as the first volume route');
assert.doesNotMatch(intro, /首 次 推 薦/, 'B1 should avoid recommendation-platform wording');
assert.match(intro, /先 往 上 海 · 朱 砂 印 已 亮/, 'B1 first map hint should name the immediate first step');
assert.match(intro, /const MAP_COACH = \[[\s\S]*朱 砂 所 指[\s\S]*四 方 風 聲/, 'B1/C map coach should stay short and in-world');
assert.doesNotMatch(intro, /先花一分鐘認識畫面|① 當 前 要 務|② 另 可 探 訪|⑤ 見 識 三 軸/, 'B1 coachmark should not return to long tutorial labels');
assert.match(css, /B1 · First 5 Minutes Polish[\s\S]*\.screen--intro \.bottom-strip[\s\S]*opacity:\s*0\.42/, 'B1 should visually de-emphasise landing utility buttons without disabling them');
assert.match(intro, /const MAP_COACH = \[[\s\S]*朱砂印[\s\S]*青綠印[\s\S]*四 方 風 聲/, 'C should keep map coach focused on target, side visits, and resistance context');
assert.match(intro, /const MAP_COACH = \[[\s\S]*史 · 事[\s\S]*手 卷[\s\S]*見 識[\s\S]*舊 友 新 知/, 'C3 map coach should explain events, journal, insight, and people panels');
assert.match(intro, /const CITY_COACH = \[[\s\S]*先 看 紅 點[\s\S]*所 見[\s\S]*查 證[\s\S]*史 事 抉 擇/, 'C should teach the city loop in staged in-world prompts');
assert.match(intro, /function finishCityCoachOutcome\(\)[\s\S]*markCityIntroSeen\(gameState\.currentCity\)[\s\S]*resumePinnedAfterCoreLoop\(\)/, 'C3 should resume deferred history events after city teaching is completed or skipped');
assert.match(intro, /function shouldProtectFirstCityEntry\(cityKey\)[\s\S]*citiesIntroduced/, 'C should define a first-city entry protection helper');
assert.match(intro, /function markCityIntroSeen\(cityKey\)[\s\S]*citiesIntroduced/, 'C should mark city intro guidance as seen');
assert.match(intro, /function shouldDeferPinnedForCoreLoop\(ev,\s*onCityEnter\)[\s\S]*coachmark:not\(\[hidden\]\)/, 'C should defer pinned events while core-loop guidance is active');
assert.match(intro, /checkAndTriggerPinned\(true\)[\s\S]*shouldDeferPinnedForCoreLoop/, 'C should route city-entry pinned events through the deferral guard');
assert.match(intro, /hideHotspotObservation\(\);[\s\S]*openEvidenceTask\(cityKey,\s*hs,\s*btn\)/, 'C should hide observation text before opening the evidence task');
assert.match(css, /Sprint C · Core Loop Clarity[\s\S]*\.screen--selection[\s\S]*background/, 'C should include selection-page visual unification styles');
assert.match(css, /Sprint C · Core Loop Clarity[\s\S]*\.em-choice[\s\S]*border-left/, 'C should restyle event choices as archive decisions');
assert.match(css, /Sprint C · Core Loop Clarity[\s\S]*\.hotspot-observation[\s\S]*max-width/, 'C should include hotspot observation layering refinements');
assert.match(intro, /function getHotspotObservationAnchor\([\s\S]*gapX[\s\S]*gapY/, 'C2 should compute close-range hotspot observation anchors');
assert.match(intro, /showHotspotObservation\(hs,\s*btn\)[\s\S]*openHotspot\(hs,\s*btn\)/, 'C2 should keep tap-to-observe before tap-to-open behavior');
assert.match(intro, /function hasPendingPinnedInCurrentCity\(\)[\s\S]*findDueTravelPinned\(\)/, 'C2 should detect deferred pinned events in the current city after evidence completion');
assert.match(intro, /function finishEvidenceReveal\(hs\)[\s\S]*resumePinnedAfterCoreLoop\(\)[\s\S]*openEvent\(hs\.unlocks\)/, 'C2 should resume deferred pinned events from evidence completion before optional hotspot events');
assert.match(intro, /function resumePinnedAfterCoreLoop\(\)[\s\S]*checkAndTriggerPinned\(true\)/, 'C2 should keep a single post-evidence pinned resume helper');
assert.match(css, /Sprint C2 · Core Loop Feel Polish[\s\S]*\.hotspot-observation[\s\S]*--ho-gap-x/, 'C2 should position observation copy near the red-dot clue');
assert.match(css, /Sprint C2 · Core Loop Feel Polish[\s\S]*\.screen--selection \.s2c-slide[\s\S]*min-height:\s*100%/, 'C2 should make character selection feel like one full cinematic stage');
assert.match(css, /Sprint C2 · Core Loop Feel Polish[\s\S]*\.screen--selection \.s2c-portrait-wrap[\s\S]*mask-image/, 'C2 should visually blend portraits into the shared scene');
assert.match(css, /Sprint C2 · Core Loop Feel Polish[\s\S]*\.screen--selection \.s2c-tags[\s\S]*opacity:\s*0\.[0-7]/, 'C2 should demote route stats and tags below the character mood');
assert.match(intro, /function gotoSelectionFromMap\(\)[\s\S]*stage\.classList\.add\('is-on-selection'\)/, 'C3 restart route should return to the character selection screen state');
assert.match(css, /Sprint C3 · First Loop Repair[\s\S]*\.screen--selection \.s2c-portrait-wrap[\s\S]*inset:\s*0/, 'C3 should dissolve the character portrait into a shared full-stage composition');
assert.doesNotMatch(intro, /dot\.setAttribute\('aria-label',\s*`跳至 \$\{c\.name\}`\)/, 'Character selection dots should not reveal the full roster by name');
assert.match(intro, /dot\.setAttribute\('aria-label',\s*`第 \$\{i \+ 1\} 位見證者`\)/, 'Character selection dots should use generic witness labels');
assert.doesNotMatch(intro, /const portrait = e\.target\.closest\('\.s2c-portrait-wrap'\);[\s\S]*slide\.classList\.toggle\('is-flipped'/, 'Character selection portraits should not open a foreground ability/stat flip panel');
assert.match(css, /Sprint D1 · Character Selection Redesign[\s\S]*\.screen--selection \.s2c-ability-panel(?:\s*,[^{]*|\s*)\{[^}]*display:\s*none\s*!important/, 'Character selection should hide ability panels from the first reading layer');
assert.match(css, /Sprint D1 · Character Selection Redesign[\s\S]*\.screen--selection \.s2c-tags(?:\s*,[^{]*|\s*)\{[^}]*display:\s*none\s*!important/, 'Character selection should hide route tags and stars from the first reading layer');
assert.match(css, /Sprint D1 · Character Selection Redesign[\s\S]*\.screen--selection \.s2c-cta(?:\s*,[^{]*|\s*)\{[^}]*width:\s*min\(242px,\s*72vw\)/, 'Character selection CTA should be visually shorter and focused');
assert.match(css, /Sprint D1 · Character Selection Redesign[\s\S]*\.screen--selection \.s2c-arrow(?:\s*,[^{]*|\s*)\{(?=[^}]*min-width:\s*52px)(?=[^}]*min-height:\s*52px)[^}]*\}/, 'Character selection arrows should remain comfortable touch targets');
assert.match(intro, /function choiceMetaLabel\(choice\)[\s\S]*return '抉 擇'/, 'Event choice metadata should be immersive rather than axis-labelled');
assert.match(css, /\.em-continue[\s\S]*min-height:\s*(44|46)px/, 'Event continue buttons should keep comfortable touch targets');
assert.doesNotMatch(html, /求知考驗/, 'Event rhythm should avoid exam-like challenge language');
assert.match(html, /id="emChallengeFrame"/, 'Event challenge should use a framed challenge area');
assert.match(html, /id="emResultFrame"/, 'Event result should use a framed result area');
assert.match(intro, /function getChoiceImpactText\(choice\)/, 'Event choice impact text should be generated by a helper');
assert.match(css, /\.em-challenge-frame[\s\S]*border/, 'Challenge frame should have a visible frame');
assert.match(css, /\.em-result-frame[\s\S]*border/, 'Result frame should have a visible frame');
assert.match(css, /\.em-challenge-opt[\s\S]*min-height:\s*44px/, 'Challenge options should keep comfortable touch targets');
assert.match(html, /幕 僚 追 問/, 'Challenge UI should use in-world role questioning language');
assert.match(html, /擇 一 回 應 · 只 可 定 奪 一 次/, 'Challenge note should avoid exam-like scoring language');
assert.match(intro, /function getChallengeSpeaker\(ev,\s*ch\)/, 'Challenge speaker should be generated by a helper');
assert.match(intro, /所 斷 可 取/, 'Correct result should use in-world judgement language');
assert.match(intro, /尚 待 斟 酌/, 'Incorrect result should use in-world judgement language');
assert.doesNotMatch(intro, /求 知 考 驗 →/, 'Event continue copy should not expose quiz language');
assert.doesNotMatch(intro, /正解：/, 'Result feedback should avoid exam-like answer labels');

assert.match(html, /type="module"\s+src="\/src\/main\.js"/, 'index.html should use Vite module entry after migration');
assert.match(main, /import '\.\/research\/version\.js';/, 'main.js should load research version before game code');
assert.match(main, /import '\.\/research\/logger\.js';/, 'main.js should load local research logger before game code');
assert.match(main, /import '\.\/research\/instrumentation\.js';/, 'main.js should load local research instrumentation before game code');
assert.match(main, /import '\.\/research\/session\.js';/, 'main.js should load research session helper before game code');
assert.match(main, /import '\.\/research\/login-gate\.js';/, 'main.js should load research login gate after session helper');
assert.doesNotMatch(main, /research\/api\.js/, 'main.js should not reference backend API helper before login/submission UI exists');
assert.match(version, /APP_VERSION\s*=\s*'dev-v0\.1'/, 'APP_VERSION should start as dev-v0.1');
assert.match(version, /RESEARCH_COHORT\s*=\s*'lkkc-may-june-2026'/, 'Research cohort should match the planned school period');
assert.match(version, /window\.__APP_VERSION\s*=\s*APP_VERSION/, 'APP_VERSION should be exposed for QA and future logging');
assert.match(version, /document\.documentElement\.dataset\.appVersion\s*=\s*APP_VERSION/, 'APP_VERSION should also be exposed as an HTML data attribute');
assert.match(logger, /yangwu_research_event_queue_v1/, 'Research logger should use a dedicated local queue key');
assert.match(logger, /window\.__researchLog/, 'Research logger should expose a QA hook');
assert.match(logger, /APP_VERSION/, 'Research logger should attach app version to each event');
assert.match(logger, /RESEARCH_COHORT/, 'Research logger should attach research cohort to each event');
assert.match(logger, /document\.documentElement\.dataset\.researchLogger\s*=\s*'local-v1'/, 'Research logger should expose a browser-readable QA marker');
assert.match(logger, /document\.documentElement\.dataset\.researchQueueKey\s*=\s*QUEUE_KEY/, 'Research logger should expose the local queue key as a QA marker');
assert.match(session, /yangwu_research_session_v1/, 'Research session should use a dedicated sessionStorage key');
assert.match(session, /sessionStorage/, 'Research session should use sessionStorage for current browser session state');
assert.match(session, /window\.__researchSession/, 'Research session should expose a QA hook');
assert.match(backendApi, /\/api\/login/, 'Research API helper should target login route');
assert.match(backendApi, /\/api\/logs-batch/, 'Research API helper should target log batch route');
assert.match(backendSchema, /create table intervention_runs/, 'Schema should include intervention fidelity layer');
assert.match(backendSchema, /complexity_dimensions/, 'Schema should include historical complexity dimensions');
assert.match(backendSchema, /create table derived_indicators/, 'Schema should include analysis-ready derived indicators');
assert.match(backendSchema, /rubric_version/, 'Schema should include rubric versioning');
assert.match(backendSchema, /instrument_version/, 'Schema should include instrument versioning');
assert.match(taxonomy, /SOURCE_OPENED:\s*'source_opened'/, 'Event taxonomy should include source_opened');
assert.match(taxonomy, /CHECKPOINT_SUBMITTED:\s*'checkpoint_submitted'/, 'Event taxonomy should include checkpoint_submitted');
assert.match(taxonomy, /SESSION_START:\s*'session_start'/, 'Event taxonomy should include session_start');
assert.match(taxonomy, /document\.documentElement\.dataset\.researchEventTaxonomy\s*=\s*'yangwu-v1'/, 'Event taxonomy should expose a browser-readable QA marker');
assert.match(intro, /__yangwuResearch\?\.logSessionStart/, 'Task 7 should log session_start from game flow');
assert.match(intro, /__yangwuResearch\?\.logCityEntered/, 'Task 7 should log city_entered from game flow');
assert.match(intro, /__yangwuResearch\?\.logEvidenceTaskCompleted/, 'Task 7 should log evidence_task_completed from game flow');
assert.match(intro, /__yangwuResearch\?\.logEventOpened/, 'Task 7 should log event_opened from game flow');
assert.match(intro, /__yangwuResearch\?\.logDecisionSelected/, 'Task 7 should log decision_selected from game flow');
assert.match(intro, /__yangwuResearch\?\.logSessionEnd/, 'Task 7 should log session_end from game flow');
assert.doesNotMatch(intro, /choice_label\s*:/, 'Task 7 decision logging should not store visible choice prose');

console.log('stability checks passed');
